### ISSUE TITLE
Tag Version Control the website

### ISSUE THREAD

**Issue by StephenOTT** [CityofOttawa/Apps4Ottawa-Website#1]
Need to generate some Tags in Git for tracking the different versions of the Website.

Currently in the Repo is the 2012 version.  This should be tagged so people can load older versions of the website if they wanted too.

May also want to consider just creating separate branches or repos

**Comment by StephenOTT** [comment]
@nickjs for your consideration

**Comment by StephenOTT** [comment]
@giggey For your consideration

**Comment by giggey** [comment]
Sorry, I honestly don't understand what this means, or more accurately how to tag something?  Actually don't even know how branching works (assuming this is where you take a base program and it will split into various iterations of the program), e.g. the Apps4Ottawa 2 site that Nick is working on would be a branch of the original.

**Comment by StephenOTT** [comment]
The branches usually get merged, and your definition is correct.

For the Tags, is basically a way to mark the versions.  It is do using Git in the command line.
Before @nickjs does any additional commits he should be able to generate a tag for the 2013 version of the website

**Comment by StephenOTT** [comment]
See this example from the WET-BOEW repo:
Branches:
![Branch](https://f.cloud.github.com/assets/1994838/69056/cabe49fc-5f4c-11e2-87ee-069f823c6e05.png)

Tags:
![Tags](https://f.cloud.github.com/assets/1994838/69059/d342b8ec-5f4c-11e2-89a0-27bdb4208778.png)

There is overlap between the two when a branch is currently live.  But to track each iteration over time, Tags are used
When the tag is changed, you see the code repository change to provide the code for that time period/tag

**Comment by giggey** [comment]
Makes sense to me.  Anything that helps improve the site, encourages others to use and develop on it, and thus provides us with an even better site down the road would be great.

**Comment by nickjs** [comment]
Sure, tagging releases is always a good idea. I've gone ahead and tagged the 2011 version.
